# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  create-change:
    runs-on: ubuntu-latest
    needs: build
    name: 'ServiceNow DevOps Change Automation'

    steps:
    - name: ServiceNow DevOps Change Automation
      uses: ServiceNow/servicenow-devops-change@v4.0.0
      with:
        instance-url: ${{ secrets.INSTANCE_URL }}
        devops-integration-token: ${{ secrets.DEVOPS_INTEGRATION_TOKEN }}
        tool-id: ${{ secrets.TOOL_ID }}
        job-name: 'ServiceNow DevOps Change Automation'
        context-github: ${{ toJSON(github) }}
        timeout: '3600'
        interval: '100'
        # The customized inputs to create change with the requested details.
        change-request: '{"setCloseCode": "true","autoCloseChange": true,"attributes": {"chg_model":{"name":"DevOps"},"short_description": "Sprint Runner Change created from pipeline","description": "GitHub Automated Software Deployment.","assignment_group": "a715cd759f2002002920bde8132e7018","assigned_to" :{"name": "Abraham Lincoln"},"work_notes": "Check out this awesome CR","implementation_plan": "Software update is tested and results can befound in Test Summaries Tab","backout_plan": "When software fails in production, the previous software release will be re-deployed.", "software_model": "273e27a783cc5a10b5f681b8beaad3d7", "test_plan": "Testing if the software was successfully deployed"}}'
        # The max. time in seconds to wait until change created.
        changeCreationTimeOut: '3600'

  publish-package:
    runs-on: ubuntu-latest
    needs: create-change

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
  
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      # - name: Publish to GitHub Packages Apache Maven
      #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}